=== RemcoTukker/swarm-control/src/edu/cmu/ri/createlab/terk/impression/impression.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT impression (info?,services)>
<!ATTLIST impression
   version CDATA       #REQUIRED
>

<!ELEMENT info (name,description?,created-timestamp?)>
<!ELEMENT name ANY>
<!ELEMENT description ANY>
<!ELEMENT created-timestamp ANY>

<!ELEMENT services (service+)>

<!ELEMENT service (operation+)>
<!ATTLIST service
   type-id  CDATA    #REQUIRED
>

<!ELEMENT operation (device+)>
<!ATTLIST operation
   name     CDATA    #REQUIRED
>

<!ELEMENT device (parameter*)>
<!ATTLIST device
   id       CDATA    #REQUIRED
>

<!ELEMENT parameter ANY>
<!ATTLIST parameter
   name     CDATA    #REQUIRED
>

=== RemcoTukker/swarm-control/src/edu/cmu/ri/createlab/terk/impression/ExampleImpression.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE impression PUBLIC "-//CREATE Lab//TeRK//Impression//EN" "http://www.createlab.ri.cmu.edu/dtd/terk/impression.dtd">

<impression version="1.0">
   <info>
      <name><![CDATA[Hello World]]></name>
      <description><![CDATA[This is a description]]></description>
      <created-timestamp>1207926600000</created-timestamp>
   </info>
   <services>
      <!-- ANALOG INPUTS -->
      <service type-id="::TeRK::analog::AnalogInputsService">
         <operation name="getAnalogInputValue">
            <device id="0"/>
         </operation>
      </service>

      <!--
      Here is another example for the Analog Inputs Service...

      <service type-id="::TeRK::analog::AnalogInputsService">
         <operation name="getAnalogInputValues">
            <device id="0"/>
            <device id="1"/>
            <device id="2"/>
         </operation>
      </service>
      -->

      <!-- THERMISTOR -->
      <service type-id="::TeRK::thermistor::ThermistorService">
         <operation name="getThermistorValue">
            <device id="2"/>
         </operation>
      </service>
   </services>
</impression>
